### ISSUE TITLE
Getting "undefined method `creds'" when I run this in staging environment

### ISSUE THREAD

**Issue by hesham** [freeletics/creds#3]
Works fine in development and test environments.

Error:
```
  NoMethodError: undefined method `creds' for #<Rails::Application::Configuration:0x00005637fdcf8d80>
  /var/app/ondeck/config/environments/staging.rb:74:in `block in <top (required)>'
  /var/app/ondeck/config/environments/staging.rb:3:in `<top (required)>'
  /var/app/ondeck/config/environment.rb:7:in `<top (required)>'
  /opt/rubies/ruby-2.5.1/bin/bundle:23:in `load'
  /opt/rubies/ruby-2.5.1/bin/bundle:23:in `<main>'
  Tasks: TOP => environment
  (See full trace by running task with --trace) (Executor::NonZeroExitStatus)
```

Rails 5.2.0 with Ruby 2.5.1

**Comment by hesham** [comment]
Invalid. Found the issue. Order matters in the the environment file. Make sure `config.creds = ..` is set before using it further down in the file.
