### ISSUE TITLE
secret_key_base loaded in too late

### ISSUE THREAD

**Issue by InteNs** [freeletics/creds#6]
Hello, i've encountered another problem.
I've set a secret key base in my staging environment but when i load the rails console it still thinks the key is missing.

when i add a `master.key` and `config/credentials.yml.enc` with another `secret_key_base`

rails console loads fine, and `Rails.configuration.secret_key_base` corresponds to the one in `config/credentials/staging.yml.enc` **not** the one defined in `config/credentials.yml.enc`

this lets me conclude that the railtie initializer works, but is called too late in the boot cycle.

**Comment by morgoth** [comment]
What do you mean by "still thinks the key is missing"?
By default `RAILS_MASTER_KEY` env key is checked and fallbacks to `config/master.key` file.

**Comment by InteNs** [comment]
in the boot-stage where rails checks for the secret-key-base it tries to fetch it from `config/credentials.yml.enc` even though it's booting into staging so it should look in `config/credentials/staging.yml.enc`

when you add a secret_key_base in `config/credentials.yml.enc` so rails can boot succesfully and afterwards check the secret_key_base value, the value matches the one from `config/credentials/staging.yml.enc`

so creds did set the secret_key_base to the correct one.
but it does this too late, so rails had already checked for it before booting.

**Comment by morgoth** [comment]
it won't look in `config/credentials/staging.yml.enc` by default, so you need to set it via `Creds.new("config/credentials/staging.yml.enc")`

Currently in the app I don't have `config/credentials.yml.enc` at all and Rails is booting fine.
What error are you getting?

**Comment by InteNs** [comment]
it loads fine for me in RAILS_ENV=development
not in staging/production though

`config/environments/staging.rb`
```rb
Rails.application.configure do
  config.creds = Creds.new('config/credentials/staging.yml.enc', key_path: 'config/credentials/staging.key')
```

```
➜ rails c -e staging
Traceback (most recent call last):
	42: from bin/rails:4:in `<main>'
	41: from bin/rails:4:in `require'
	40: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	39: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
	38: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
	37: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	36: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	35: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	34: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/commands/console/console_command.rb:95:in `perform'
	33: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/command/actions.rb:18:in `require_application_and_environment!'
	32: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/application.rb:337:in `require_environment!'
	31: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	30: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	29: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	28: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/skylight-core-3.1.1/lib/skylight/core/probes.rb:119:in `require'
	27: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/skylight-core-3.1.1/lib/skylight/core/probes.rb:119:in `require'
	26: from /Users/intens/Projects/Fabriquartz/rail-io-api/config/environment.rb:5:in `<top (required)>'
	25: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
	24: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	23: from /Users/intens/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	22: from /Users/intens/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	21: from /Users/intens/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	20: from /Users/intens/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
	19: from /Users/intens/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
	18: from /Users/intens/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	17: from /Users/intens/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	16: from /Users/intens/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	15: from /Users/intens/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	14: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	13: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
	12: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	11: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
	10: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	 9: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
	 8: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	 7: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	 6: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	 5: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activesupport-5.2.1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
	 4: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/activestorage-5.2.1/lib/active_storage/engine.rb:67:in `block (2 levels) in <class:Engine>'
	 3: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/application.rb:205:in `message_verifier'
	 2: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/application.rb:176:in `key_generator'
	 1: from /Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/application.rb:432:in `secret_key_base'
/Users/intens/.rbenv/versions/2.5.1/gemsets/fabribackend/gems/railties-5.2.1/lib/rails/application.rb:585:in `validate_secret_key_base': Missing `secret_key_base` for 'staging' environment, set this string with `rails credentials:edit` (ArgumentError)
```

**Comment by morgoth** [comment]
If the 'config/credentials/staging.key' exists and there is `secret_key_base` defined inside encrypted staging file then it should work.
As you can see Rails is checking few places for it https://github.com/rails/rails/blob/v5.2.1/railties/lib/rails/application.rb#L432-L435 and then in https://github.com/rails/rails/blob/v5.2.1/railties/lib/rails/application.rb#L402

`creds` gem is setting `config.secret_key_base` so the last fallback option.
Hard to guess what's wrong here.

**Comment by morgoth** [comment]
Please reopen if you still have the problem

**Comment by InteNs** [comment]
i've stopped using this gem :(
completely forgot about this issue, sorry about that.

**Comment by morgoth** [comment]
Thanks for info.
BTW did you switch to other solution or do you use vanilla Rails to handle it?

**Comment by InteNs** [comment]
We had to change a lot in our infrastructure and dockerized the whole app.

- docker swarm places a .env file with secrets.
- dotenv gem loads the .env file into rails environment.
